### ISSUE TITLE
Unannounced dependencies

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvsim#106]
pyuvsim won't install without LineProfiler installed.  Are we OK with this as a dependency?

**Comment by jpober** [comment]
Same goes for yaml (I suspect we do need this one)

**Comment by jpober** [comment]
... and mpi4py (almost certainly required)

**Comment by jpober** [comment]
Install works, but two of our tests in nosetests also requires memory_profiler

**Comment by mkolopanis** [comment]
I know the profilers have been very helpful diagnosing how the task list behaves and identifying areas of improvement, but I guess I'll just reverberate jonnie's question of whether this would be necessary for a "release" product (e.g. should we remove these from master before version 1.0.0)?

**Comment by bhazelton** [comment]
I'm in favor of leaving them. Keeping forks up to date is a pain.

**Comment by mkolopanis** [comment]
yeah forking can be a nightmare. I don't mind if they stay :smile: let's just add them to the required list then.

**Comment by jpober** [comment]
Sounds reasonable, I just wanted to document all the unexpected dependencies as I did an install from scratch.  Is there a relatively simple way to do what we had done with progress_bar, e.g., run the profiler if it's installed, but skip it if it isn't?  If not, let's just leave them in for now.

**Comment by aelanman** [comment]
That should be do-able. Just wrap `from line_profiler import LineProfiler` in a try/except block and skip the rest of `profiling.py` if it's not imported successfully. It'd be nice if we could have it raise a warning if someone tries to run with profiling when the module isn't available. I'm not sure how best to handle the profiling in the unit tests.
