### ISSUE TITLE
Make unit tests that use multiple MPI ranks

### ISSUE THREAD

**Issue by aelanman** [RadioAstronomySoftwareGroup/pyuvsim#126]
More and more I'm finding bugs that only come up when running a simulation with more than one rank. Although we test the MPI framework, we don't actually do any unit tests with multiple processing units. I believe it is possible to run nosetests with mpirun, but it would probably require adjusting how we call them in travis.

Adding to the First release milestone, because I don't think we can really trust our code coverage unless this is achieved.

**Comment by bhazelton** [comment]
Do you think running with multiple ranks gives different results than a single rank in the existing architecture (no local task generation)?

**Comment by aelanman** [comment]
I can't say for certain if it affects the results calculated on master, and I wouldn't expect it to given how it's parallelized, but as we try other algorithms it might become an issue.

There have been times when all unit tests pass but running a simulation crashes because of some problem on a different rank. For example, we had an issue for a while where UVBeam objects weren't interpolating after being scattered, and it only came up when running an actual simulation with a wrapper script. So a PR could break things despite passing all checks.

**Comment by bhazelton** [comment]
That makes sense. I agree we need to have test coverage that protects us from making mistakes as we go forward with architectural changes.

**Comment by mkolopanis** [comment]
It looks like there is no good plugin for at least `pytest` to get mpi code executed on _some_ tests. The more I look the more it seems like tests should be build to be executed with an `mpiexec` call from the ground up.

**Comment by jpober** [comment]
We can create a set of tests that don't run as unit tests but are run for major PRs.  Once created, we should add this to our PR template.

**Comment by jpober** [comment]
Perhaps create a new folder of MPI tests and run separately.

**Comment by aelanman** [comment]
Several lines are currently skipped by coverage because they can only be reached by a multi-process test. When such testing is added, those uncovered lines should be re-examined.
