### ISSUE TITLE
Test coverage

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvsim#130]
README says we're aiming for 97%.  So let's do that.

**Comment by aelanman** [comment]
Coverage has dropped below 97% again. Much of this loss is from the addition of the spherical basis functions, which are being moved to `pyradiosky`, so this may be resolved by the `remove_skymodel` branch. Some of the uncovered lines are part of Steven's fixes to allow installation without installing mpi4py.
