### ISSUE TITLE
Make a HERA simulation with LTG2

### ISSUE THREAD

**Issue by dannyjacobs** [RadioAstronomySoftwareGroup/pyuvsim#133]
We think local task generation can probably give an order of magnitude speedup over master. Next step is to figure out whether this is true and then decide what the simulation parameters of a bigger sim would be.
Danny suggests x10 more times. Jonnie is a fan of more sources.

**Comment by aelanman** [comment]
Assuming this meets the standards of this issue, here are the results from GLEAM and Fornax model simulations using an airy beam with diameter=14.6m:

Simulated data:
![hera65_sim_waterfall_bl155-2](https://user-images.githubusercontent.com/12849618/49664156-0cc57f00-fa1f-11e8-8674-9e0e151278a2.png)

Uncalibrated, unflagged raw HERA data:
![hera65_data_waterfall_bl155-2](https://user-images.githubusercontent.com/12849618/49664157-0cc57f00-fa1f-11e8-83ec-02fdb6c43aa9.png)

Fornax imaging simulation:
![fornax_airy_mwa88_im image](https://user-images.githubusercontent.com/12849618/49664158-0cc57f00-fa1f-11e8-866b-59c42a852cf4.png)

**Comment by jpober** [comment]
This closes this issue, but we'll leave the HERA Sim milestone open.
