### ISSUE TITLE
Optimize memory usage in local task generation

### ISSUE THREAD

**Issue by aelanman** [RadioAstronomySoftwareGroup/pyuvsim#134]
It's looking like we might just merge the LTG branch anyway, but this should be addressed. There should be a pretty simple solution that lets us avoid copying over the full simulation configuration to each rank.

Three options for catalogs in particular:
1. Scatter catalog paths (or mock keywords) and modify catalog readers to have a "select" option. Becomes disk I/O intensive, but this only has to happen once per run.
2. Put the full catalog as a numpy array in a memory window (or a handful of them, for multi-node architecture), select required entries and generate source objects on rank.
3. Figure out, based on the numbers of tasks and MPI PUs, which sources will be needed by each rank. Scatter these, along with information on the total number of sources.

**Comment by jpober** [comment]
Not currently necessary, but still possibly useful improvement for future.

**Comment by jpober** [comment]
Option 1 probably won't happen.  But other two are still interesting to consider one day.

**Comment by jpober** [comment]
Option #2 was effectively implemented for catalogs.  Similar solution might be possible for UVBeams.

**Comment by jpober** [comment]
This has been done.
