### ISSUE TITLE
Frequency dependent gaussian beam

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvsim#144]
Should have option for some simple (e.g. linear) frequency dependence in our analytic beams.

**Comment by aelanman** [comment]
I've started working on this. The Airy beam option already has frequency dependence, and the Gaussian beam is defined by a fixed width. I can add a frequency scaling to it if that's still wanted, but I've been doing the HERA simulations with an Airy beam anyway.

**Comment by jpober** [comment]
Note that first reference simulations were run with a Gaussian where sigma was the input.  But future should have a diameter be the input (makes things consistent with Airy beam).

**Comment by jpober** [comment]
Some subtleties in implementation.  Once a pull request is made, have @nithyanandan @jpober @bhazelton review.
