### ISSUE TITLE
j < i

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvsim#146]
Currently pyuvsim creates baselines where antenna number j < antenna i.  This is fine as long as we're consistent -- we don't have any requirements on the antenna numbering order in baseline pairs.  But given that j > i is more "standard" perhaps we want to change it anyway?

**Comment by jpober** [comment]
Pyuvdata has some code that can help with this, but it needs to be cleaned up to help us easily address this.

**Comment by bhazelton** [comment]
RadioAstronomySoftwareGroup/pyuvdata#502

**Comment by bhazelton** [comment]
This is addressed by a PR on pyuvdata: https://github.com/RadioAstronomySoftwareGroup/pyuvdata/pull/562

**Comment by bhazelton** [comment]
This is now fully handled by pyuvdata's `reorder_blts` method.
