### ISSUE TITLE
Compare with HERA Data

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvsim#163]
A somewhat cursory comparison of pyuvsim results with a matching HERA data set to make sure there are no gross errors

**Comment by dseitova** [comment]
![waterfalls_data](https://user-images.githubusercontent.com/26636877/51563888-a32cf300-1e5b-11e9-8de2-0254cbdd8f7c.png)
![waterfalls_pyuvsim](https://user-images.githubusercontent.com/26636877/51563889-a32cf300-1e5b-11e9-9089-f3c0e60080a1.png)

**Comment by dseitova** [comment]
![waterfall_data_horizon](https://user-images.githubusercontent.com/26636877/51563926-bf309480-1e5b-11e9-9707-8071b05b1c22.png)
![waterfall_pyuvsim_horizon](https://user-images.githubusercontent.com/26636877/51563927-bf309480-1e5b-11e9-9da0-6fbf789a914d.png)

**Comment by bhazelton** [comment]
Done. see reference_simulations/memos
