### ISSUE TITLE
summary of first reference sim validation

### ISSUE THREAD

**Issue by dannyjacobs** [RadioAstronomySoftwareGroup/pyuvsim#167]
This memo will summarize the first reference simulation, what questions were we hoping to answer, what parameters did we choose and why, what did we learn from comparison with prisim outputs, and most importantly summarize the precision attained. The goal is to be able to quote a single number for how closely prisim and pyuvsim agree.

**Comment by aelanman** [comment]
The materials on the hera wiki page should be useful for this:

[http://hera.pbworks.com/w/page/128281848/pyuvsim_reference_sims_v1](http://hera.pbworks.com/w/page/128281848/pyuvsim_reference_sims_v1)

**Comment by dannyjacobs** [comment]
Some notes:
In the frequency domain they agree at 10^-5 with quantization type errors at 10^-6.
The difference shows a floor in the delay spectrum at 1e-6 which is above the expected blackman-harris floor at 1e-10
In the image domain a phase offset at roughly the psf size and can be traced to differences in uvw calculation.  Antenna positions agree to tolerance which suggests uvw difference is related to phasing.  prisim and pyvusim use different codes for phasing and time calculation. The PRISim code is not covered with analytic tests.

**Comment by dannyjacobs** [comment]
Started branch: https://github.com/RadioAstronomySoftwareGroup/pyuvsim/tree/reference_sim_writeup

**Comment by jpober** [comment]
@dannyjacobs
