### ISSUE TITLE
Memo for reference sim 1.1

### ISSUE THREAD

**Issue by dannyjacobs** [RadioAstronomySoftwareGroup/pyuvsim#168]
This will bookmark progress on the image comparison in issue #95. Should be based on results to date, need not pend on the ongoing effort to fix known issue in prisim phasing.

**Comment by dannyjacobs** [comment]
We just need the "work to date" documented showing that pyuvsim HERA simulations are "worth looking at". The evidence in #95 and elsewhere on slack seems to suggest that this is the case. This memo just brings this all together.

**Comment by bhazelton** [comment]
This is now in the repo under reference_simulations/memos
