### ISSUE TITLE
importing pyuvsim.simsetup without needing mpi

### ISSUE THREAD

**Issue by aelanman** [RadioAstronomySoftwareGroup/pyuvsim#191]
The setup tools should be accessible to other simulation packages, but accessing them requires from pyuvsim requires that mpi4py be installed, which can be difficult. We should either migrate these functions to a new repository, or allow for pyuvsim to be installed without mpi4py.

**Comment by bhazelton** [comment]
Need to be clear in docs when it is required.

**Comment by mkolopanis** [comment]
#233 Allows for _installation_ of this module without mpi4py and psutil. However our current `__init__.py` attempts to import all modules still, so importing something that requires mpi4py or lineprofiler will result in assertion errors.
