### ISSUE TITLE
Update version and tag release for JOSS

### ISSUE THREAD

**Issue by aelanman** [RadioAstronomySoftwareGroup/pyuvsim#199]
As we've discussed.

**Comment by bhazelton** [comment]
Do you want me to make a PR to do this? What version are we going to (we're currently on 0.2.1). 

Also, I was waiting on the JOSS review to try to get the conda package working. That's likely to generate a little bit of version number churn because if anything in this repo needs to be updated I have to increment the version number in order to make a new pypi package (which is required for the conda package). So I guess I want to know if you want me to do that churning before or after the big number update for JOSS.

**Comment by aelanman** [comment]
I'm not sure what the appropriate procedure is here. A snapshot of the code gets saved to Zenodo when the paper is accepted, but I'm not sure if we need to make a new release before that happens. Do you remember what happened with pyuvdata? Also, do you think it's worth raising the version number as well?

**Comment by jpober** [comment]
I'm looking at our versioning description, and I guess I'm trying to tell what would warrant moving to 1.x.x (i.e. a new generation).  It seems like vector_sources would warrant a new generation if/when it's finished.  Does it make sense for the JOSS referenced code to be version 1.0.0?  We've decided that it's going to be the defining point for our reference simulations, so it seems like it warrants at least a new major version number (like 0.3.0).

**Comment by aelanman** [comment]
I think the major generation changes are only supposed to happen when there is a change to the API, such that software using version 1.0 should not be expected to be instantly compatible with 2.0, etc. We were going to hold off on version 1.0 until we were sure the API was stable.

**Comment by jpober** [comment]
That makes sense, but it's not exactly what's written in the documentation.  So perhaps we should update the documentation.

**Comment by bhazelton** [comment]
Votes from the telecon:
Mat, Danny, Nithya: 1.0.0
because of the publication.

**Comment by jpober** [comment]
@bhazelton I've enabled Zenodo.  Now there's still the question (as I understand it) as to whether the release that gets published in the JOSS paper has conda/pypi packages.  I think it's OK to up to 1.0.0 now, published in JOSS, and then get conda/pypi working as 1.0.1?

**Comment by bhazelton** [comment]
yes, I think that's fine. We can put out a pypi 1.0.0, it's just the conda package that's going to take some cycling.

**Comment by bhazelton** [comment]
The 1.0.0 pypi package is up
