### ISSUE TITLE
need coherency_local calc

### ISSUE THREAD

**Issue by dannyjacobs** [RadioAstronomySoftwareGroup/pyuvsim#2]
Need a matrix to rotate a Jones matrix from RADec to AzEl.

**Comment by dannyjacobs** [comment]
Coherency calculation now has the rotation matrix part but now requires a parallactic angle calculation.  See notes in uvsim.py Source.coherency_calc.

**Comment by dannyjacobs** [comment]
We grabbed some calculation from astroplan which seems right. Now it needs to be tested.

**Comment by jpober** [comment]
Work in progress to address in pull request #19.  Missing tests and any code that actually calls these code changes -- currently has bypass for Stokes I and that needs to be removed.

**Comment by jpober** [comment]
@jaguirre Can we get an update on this issue?

**Comment by jpober** [comment]
@bhazelton @jaguirre Updates?

**Comment by bhazelton** [comment]
Getting close. I think we have all the code, James is working on test coverage. Should have it done in the next week.
