### ISSUE TITLE
docs outdated

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyuvsim#205]
https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/392a658f5713b810a269e4475b11fb96c9765c3c/pyuvsim/simsetup.py#L969

in fact, ``keep_path`` doesn't exist.

**Comment by jpober** [comment]
This line seems to be gone, but we'll keep vigilant for further outdated docs.
