### ISSUE TITLE
No way to set beam interpolation methods from parameters.

### ISSUE THREAD

**Issue by aelanman** [RadioAstronomySoftwareGroup/pyuvsim#206]
As it's currently written, beam interpolation is 'linear' by default (see [scipy.interp1d](https://docs.scipy.org/doc/scipy/reference/generated/scipy.interpolate.interp1d.html)). This causes the peaks in the visibility function:
![bad_freq_interp](https://user-images.githubusercontent.com/12849618/58295953-95eb2b00-7d9f-11e9-9380-868f0a7666a2.png)

Switching to cubic spline interpolation fixes this:
![good_freq_interp](https://user-images.githubusercontent.com/12849618/58295954-95eb2b00-7d9f-11e9-8186-8241825759db.png)

There also isn't yet a way to set the beam frequency interpolation in parameter files.

**Comment by aelanman** [comment]
The internal functions default to cubic interpolation in frequency, but I'm keeping this issue open because we should still have some way to pass along interpolation options from parameter files.

**Comment by bhazelton** [comment]
fixed in #264
