### ISSUE TITLE
Figure out what the current capabilities are

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvsim#214]
Be able to tell people what is currently doable in ~1 day of computing.
How long with a full HERA or current HERA take?

Notes:
Full GLEAM (not with Ruby's additions) with MWA phase 1, analytic beams, 1 time, 10 freqs: 25 minutes (on vectorized sources branch).

**Comment by jpober** [comment]
@kbharatgehlot Can you add some info from your slides and/or the results of your upcoming MWA Phase I obsid sim?

**Comment by kbharatgehlot** [comment]
Here are a few slides summarizing the tests we have performed on ASU agave cluster.
https://docs.google.com/presentation/d/1cbR4VfWdNacry6gsEVf1-e94ra52Wsp0CplCGq-oLp8/edit?usp=sharing

**Comment by jpober** [comment]
@dannyjacobs What do you think needs get done to close this?
