### ISSUE TITLE
IERS table download

### ISSUE THREAD

**Issue by aelanman** [RadioAstronomySoftwareGroup/pyuvsim#219]
Same problem that pyuvdata had. Travis installs astropy and tries to download IERS tables, which can fail if the usno server is down. We need to add some code to ignore the "out of time range" warnings.

This should probably be done with Matt's nose_to_pytest branch.

**Comment by mkolopanis** [comment]
I have added the iers check from pyuvdata in my branch. However we can push something very quickly to merge in too if desired.
