### ISSUE TITLE
Define second reference simulations

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvsim#223]
Need to identify exactly what we want to simulate.

**Comment by bhazelton** [comment]
I'd like one with long time, frequency and baseline axes but just one source.
maybe ~10 minutes, 100-1k frequencies, MWA no core layout.

**Comment by jpober** [comment]
Do we want a more comprehensive / accessible set of reference simulations done with vector sources and no new physics?

**Comment by jpober** [comment]
We have things defined in a Google Doc (on our slack channel).  Need to get that info posted to the repo.
