### ISSUE TITLE
Docstring uniformity

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyuvsim#230]
It seems that docstrings are generally not uniformly written in numpydoc style. It would be useful to fix/check/enforce this.

**Comment by jpober** [comment]
We will enforce numpydoc style.  Need to go through and update old docstrings.

**Comment by bhazelton** [comment]
+1

When we do this we should uncomment the docstring related flake8 checks in the pre-commit hook and add `D` to the list of flake8 tests in `setup.cfg`

**Comment by jpober** [comment]
@aelanman and @mkolopanis are going to see how places we still have bad docstrings using the flake8 checks to help determine whether this is small issue or a large one.

**Comment by jpober** [comment]
There is an open branch that needs to be rebased and then have more work done to close this.
