### ISSUE TITLE
New release

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvsim#231]
We're currently on 1.0.0, our JOSS release.  vector_sources should be a new version, 1.1.0.

**Comment by jpober** [comment]
The above comment is incorrect.  We're on 1.1.0, we just haven't released it.  A 1.1.0 release is probably warranted though.  I've changed the name of this issue to better represent the problem.

**Comment by jpober** [comment]
We can look into tools for helping to make releases more frequently.

**Comment by steven-murray** [comment]
`pyuvsim` is using `travis` right? If so: https://docs.travis-ci.com/user/deployment/pypi/

**Comment by steven-murray** [comment]
In saying that, I've had trouble in the past with the password encryption thing there. Hopefully it works for us. If we want to do this, I guess the person to do it is the one who has the current rights to the PyPI distribution.

**Comment by steven-murray** [comment]
Did we want to try this? @bhazelton ? @jpober ?
