### ISSUE TITLE
Estimate run time for 1 night of IDR 2.x

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvsim#236]
1024 channels
6 hours
10 s cadence
50 antennas (from HERA IDR 2.x)
GLEAM + healpix (res. set by longest baseline) (flat spectrum)

**Comment by aelanman** [comment]
![Figure_1](https://user-images.githubusercontent.com/12849618/64202180-89767400-ce5e-11e9-88bd-4d7de631b657.png)

20 tasks, 4 cpus per task.

**Comment by aelanman** [comment]
Rough estimate from line profiling data. I've summed up the per-hit time from the line profiler for the lines that contributed the most to runtime.

From a simulation with GLEAM + Nside128 HEALPix sources, the total runtime should scale as :

T = (k0 * (Nbl * Nf) + k1) * Nt

k0 = 0.0298799 sec
k1 = 0.338319 sec

For the conditions listed here, this gives a time of 891 core-hours (with a single MPI rank).
