### ISSUE TITLE
Runtime on PR template

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvsim#246]
A consistent theme I've raised is that new features shouldn't increase the run time of existing functionality (unless justified).  Is this something reasonable to add as a standard check on the PR template?  It's hard to ask someone to compare run times on their systems with quoted run times from Oscar, but maybe they could do a check both with master and their new branch?  It certainly makes a PR more onerous, but I also don't want to find out we've slowed down 10-fold and have to do some archaeology to find out why.

**Comment by aelanman** [comment]
This can probably be included with the "don't change the reference simulations" requirement, once we come up with a new reference simulation standard. In addition to comparing the ref sim data on the new branch and master, also compare run times.

**Comment by jpober** [comment]
@aelanman can you maybe get this in with the RMA gather branch?  Seems like an appropriate check for that change.
