### ISSUE TITLE
obsparams files should be relative to current YAML

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyuvsim#253]
It seems that the file paths in the obsparams YAML are interpreted relative to the working directory. I think this is surprising -- I would expect them to be interpreted relative to the YAML file itself.

**Comment by aelanman** [comment]
It looks for the path from the working directory by default, but if it fails to find the file there it will look relative to the obsparam:

https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/bf300aca019dbb0d7075ed08065beaaa5654651c/pyuvsim/simsetup.py#L657-L660

I agree that relative to the obsparam should be the default operation.

**Comment by steven-murray** [comment]
Is `config_path` here the path to the `obsparam` file?

**Comment by aelanman** [comment]
That's correct.

**Comment by steven-murray** [comment]
Hmmm, maybe I just made a mistake then. I think this issue is not an issue!
