### ISSUE TITLE
New diffuse (healpix) reference sim(s)

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyuvsim#254]
Now that healpix maps can be used natively in pyuvsim, we should create a new reference simulation (or suite of them). This is particularly important for testing simulators that _only_ support diffuse structure (eg. healvis). 

I guess the first thing to decide is whether we want a whole separate avenue of references similar in spirit to the point-source refs, or whether we add one or two more tests onto the end of the previous refs which have a couple of different sky models.

**Comment by steven-murray** [comment]
I guess the way to go here would be to do perhaps 9 simulations: three sets of three. The first set would be with a monopole sky, the next with a Gaussian blob, and the last with something like GSM. 
Each set would have a long axis and two short axes, where the axes are (time, freq, baselines). The short axes should probably have at least 2 elements bracketing reasonably values, while the long axis fills this bracket in "smoothly".

We would love to have these sims for hera-validation ASAP.

**Comment by jpober** [comment]
Some, if not all of these, have been done.  @steven-murray are you missing any of these?
