### ISSUE TITLE
revisit deprecation of sigma for gaussian analytic beams

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvsim#256]
To allow for achromatic analytic gaussian beams.

**Comment by jpober** [comment]
We need to take a look and see if the sigma (as it is currently used in its to-be-deprecated state) defines achromatic beams in the clearest way.

**Comment by bhazelton** [comment]
Let's go ahead and get rid of sigma (and the spectral index option). For achromatic beams, add an option to specify a frequency ("achromatic_ref_freq") in addition to the diameter parameter which would specify the frequency at which the beam would be calculated.

**Comment by bhazelton** [comment]
We're not going to make this change. The analytic beams are going to move to pyuvdata in the near future.
