### ISSUE TITLE
Make pyradiosky a dependency

### ISSUE THREAD

**Issue by steven-murray** [RadioAstronomySoftwareGroup/pyuvsim#257]
Looks like pyradiosky is not an auto-installed dependency. Is it supposed to be?

**Comment by jsdillon** [comment]
This is causing errors on hera_cal's tests.

**Comment by steven-murray** [comment]
And hera_sim. Although we fixed it by adding pyradiosky as a dependency for our CI builds explicitly. That shouldn't be necessary though.

**Comment by r-pascua** [comment]
Bumping this; excluding `pyradiosky` from `setup.py` is causing tests on `uvtools` to fail, since they use `hera_sim` for testing some of the plotting functions (and `hera_sim` only auto-installs `pyradiosky` for CI builds).
