### ISSUE TITLE
make new pypi release

### ISSUE THREAD

**Issue by r-pascua** [RadioAstronomySoftwareGroup/pyuvsim#266]
As of yesterday, the version of `pyuvsim` available on pypi is not compatible with the version of `pyuvdata` on pypi. The particular issue is the use of the `metadata_only` keyword in a function in `pyuvsim.simsetup`, but that issue is fixed in the current version of `pyuvsim` in master.

**Comment by bhazelton** [comment]
done. v1.1.2 is up on pypi.
