### ISSUE TITLE
develop a strategy around deprecation

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvsim#268]
Since pyuvsim is now being used as a library to help define simulation setups we need to be a little more careful about code deprecation. We should develop some plans about deprecation processes.

**Comment by jpober** [comment]
Specifically, we should attach to a specific number of versions that we'll wait to remove code.

**Comment by steven-murray** [comment]
As usual, going to put my bid in for following semantic versioning :-)
