### ISSUE TITLE
use black formatting

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvsim#272]
We've gone to this in pyuvdata and pyradiosky so it makes sense to do it here. It does make a lot of changes, so should be done when there is a break in branches/PRs.

**Comment by steven-murray** [comment]
For anyone who reads this: if you're working on a PR, it would be prudent to try to ensure that you're writing in black style -- this will make the transition easier when it does come. You can blacken a file by running `black <filename>`. I don't know if you can do parts of files though.
