### ISSUE TITLE
Script to add different simulation components together.

### ISSUE THREAD

**Issue by dannyjacobs** [RadioAstronomySoftwareGroup/pyuvsim#28]
We'll simulate different stuff like GLEAM, GSM etc separately and then add them together.

summing two pyuvdata objects which cover the same times, freqs etc will error because the sum method is designed to append.  This script will just check that two files are the same voxel span and then some the relevant data, flags, and count arrays according to however we think best.

**Comment by jpober** [comment]
pyuvdata will indeed take care of this issue, so we're closing it here.
