### ISSUE TITLE
Fix docs on first reference sim

### ISSUE THREAD

**Issue by bhazelton** [RadioAstronomySoftwareGroup/pyuvsim#290]
Apparently our tables and files are out of date (the files don't quite match the data files). Add details on how to use the new scripts to get the right files. Also make sure we have the files for all the different analytic beams (uniform, gaussian, airy).

**Comment by bhazelton** [comment]
Make sure all the config files for all the sims are present in the repo and there are not config files for sims that don't exist.

**Comment by jpober** [comment]
Still an issue @dseitova @aelanman?  I think you did some work on this, but is it finished?  Did we review?

**Comment by aelanman** [comment]
Details on how to use the scripts are in the README in pyuvsim/reference_simulations, but most of the requested changes are still pending on the `new_ref_sims` branch.

**Comment by bhazelton** [comment]
This was fixed in #317
