### ISSUE TITLE
Memory error at big_gather step

### ISSUE THREAD

**Issue by kbharatgehlot** [RadioAstronomySoftwareGroup/pyuvsim#307]
The job was run on 36 nodes with 4.6TB available memory (128G/node).
Simulation parameters:
```
Nbls: 8256
Ntimes: 56
Nfreqs: 384
Nsrcs: 283601
Tasks:  177537024.0

```
The error occurred after 'Calculations complete.' message.
```
Traceback (most recent call last):
  File "/scratch/bgehlot/PYUVsim/run_params_pyuvsim.py", line 27, in <module>
    pyuvsim.uvsim.run_uvsim(args.paramsfile)
  File "/scratch/bgehlot/pyuvsim/pyuvsim/uvsim.py", line 604, in run_uvsim
    input_uv, beam_list, beam_dict=beam_dict, catalog=catalog, quiet=quiet
  File "/scratch/bgehlot/pyuvsim/pyuvsim/uvsim.py", line 548, in run_uvdata_uvsim
    full_tasklist = mpi.big_gather(comm, summed_local_task_list, root=0)
  File "/scratch/bgehlot/pyuvsim/pyuvsim/mpi.py", line 277, in big_gather
    per_proc = [loads(rbuf[displ[ii]:displ[ii] + counts[ii]]) for ii in range(comm.size)]
  File "/scratch/bgehlot/pyuvsim/pyuvsim/mpi.py", line 277, in <listcomp>
    per_proc = [loads(rbuf[displ[ii]:displ[ii] + counts[ii]]) for ii in range(comm.size)]
MemoryError
application called MPI_Abort(MPI_COMM_WORLD, 1) - process 0
```
Pickle protocols:
```
In [2]: pickle.HIGHEST_PROTOCOL                                                                          
Out[2]: 4
In [3]: pickle.DEFAULT_PROTOCOL                                                                          
Out[3]: 3
```

**Comment by aelanman** [comment]
I am (almost) able to reproduce this error in a simpler case -- I make a set of 177537024 / 4 = 44384256.0 tasks on the rank 0 process, then broadcast them using `big_bcast`. Running this script in a SLURM job with an allocated 128 G of memory (on one node) causes the job to exceed allocated memory (i.e., a SLURM error) on the `big_bcast`. `big_bcast` uses the same pickle methods to serialize the data as `big_gather`.

It's probably some overhead of the serialization that's overflowing the memory. It's noteworthy gathering the serialized data is fine, but unpacking it (on the rank 0 process, hence, on a single node) is where the error comes up.

**Comment by dannyjacobs** [comment]
Interesting you managed to break on the  _de_ serializing step.

So how is it that this isn't solved by the hierarchical gather process? Is the hierarchy not doing the de-serializing? Does that question even make sense?

**Comment by aelanman** [comment]
The issue seems to be that it's deserializing the data from all processes on one node, so the memory overhead of pickle just needs to exceed the limit of one node. Serialization is done on only part of the total data (the part on each process).
