### ISSUE TITLE
Check and document simulations for source spectra

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvsim#319]
Functionality really lives in pyradiosky but we should check that our simulations using various kinds of source spectra make sense.  A single memo documenting all the types (particularly spectral index and sub-band, which are the newest) would be nice to have before we declare this functionality fully operational.

**Comment by bhazelton** [comment]
There is testing that the spectrum of visibilities from a single source with either sub-band or spectral index comes out correctly. Full and flat are trivial and are tested in other tests.
