### ISSUE TITLE
Draw random point sources uniformly distributed over solid angle. 

### ISSUE THREAD

**Issue by anguta** [RadioAstronomySoftwareGroup/pyuvsim#328]
https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/d571b4847b1bf884236f13994a2d79f429c8483a/pyuvsim/simsetup.py#L249

random sources are currently drawn distributed uniformly in azimuth and altitude but to get a uniform distribution per solid angle, one should actually do something like this

https://mathworld.wolfram.com/SpherePointPicking.html

**Comment by aelanman** [comment]
@anguta Hi Aaron. Could you take a look at the changes I made on this branch [here](https://github.com/RadioAstronomySoftwareGroup/pyuvsim/tree/randsrc_distr)? I think I have the correct scaling to ensure a uniform distribution by solid angle, but I'm not sure how to test it.

Thanks for catching this!

**Comment by anguta** [comment]
This looks good to me!

One way you might test this is drawing a large number of sources, then computing the number density per solid angle in several equal solid angle regions (taking equal area theta bins for example) and making sure they are within some tolerance. Another way is to take the sources, grid them to healpix (where the pixels all have equal areas) and then at the end of the day make sure that all the pixels have the same flux. 

cheers,

-Aaron
