### ISSUE TITLE
Failed Developer Installation through environment.yml

### ISSUE THREAD

**Issue by JianrongTan** [RadioAstronomySoftwareGroup/pyuvsim#330]
Running `conda env create -f environment.yml` will return 

```
PackagesNotFoundError: The following packages are not available from current channels:
  - pyradiosky
```
I found it was solved by deleting the line `- pyradiosky` under `dependencies`. And `pyradiosky ` is actually installed via 
```
- pip:
    - pyradiosky>=0.1.0
```

**Comment by bhazelton** [comment]
Thank you for reporting this @JianrongTan! It looks like we had pyradiosky in both the conda and pip section for some reason when it can only be installed via pip.
