### ISSUE TITLE
Barrier after return

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyuvsim#348]
I'm not really sure what it is that this does, but we have a barrier after a (possible) return statement which doesn't make a lot of sense to me.

https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/b94f5cb26609d10e99a9991ecb84f3bb6a5e033b/pyuvsim/uvsim.py#L618-L621

**Comment by aelanman** [comment]
Oooh... that's bad. That should not be there.
