### ISSUE TITLE
Default file format

### ISSUE THREAD

**Issue by mkolopanis** [RadioAstronomySoftwareGroup/pyuvsim#376]
This came up in #375, should we still default to uvfits file format? Pyuvdata does have the uvh5 format now which could be nice, but would then restrict the output to being read explicitly by pyuvdata (by default). Obviously this isn't a huge issue since the user could select a file format which has a wider implementation of readers.

**Comment by bhazelton** [comment]
@jpober and I are in favor.

**Comment by jpober** [comment]
Let's make sure however that it's very visibly documented that many file formats are possible.
