### ISSUE TITLE
Non-real values of auto-correlations failed to pass the check of pyuvdata

### ISSUE THREAD

**Issue by JianrongTan** [RadioAstronomySoftwareGroup/pyuvsim#399]
I have ran into an error when writing the outputs of pyuvsim to disk. 

`ValueError: Some auto-correlations have non-real values in data_array. You can attempt to fix this by setting fix_autos=True.`

It seems pyuvsim.utils.write_uvdata has no controls on the parameter fix_autos (fix_autos is defaultly set to be false otherwise).

**Comment by bhazelton** [comment]
@JianrongTan this has been fixed now, please let us know if you have any further issues! Note that I'm separately making a PR on pyuvdata to inform the user what the maximum size of the imaginary component is when autos are detected to be complex.
