### ISSUE TITLE
`initialize_uvdata_from_params` always returns a UVData with `integration_time=1` if `Ntimes=1`

### ISSUE THREAD

**Issue by piyanatk** [RadioAstronomySoftwareGroup/pyuvsim#427]
As in the title, `initialize_uvdata_from_params` always returns a UVData with `integration_time=1` if `Ntimes=1`. `pyuvsim` version used is `1.2.5`

**Comment by bhazelton** [comment]
@steven-murray @piyanatk Is this still something you're unhappy with? I'm concerned that it's not well-defined, see my earlier comment. Should we just update the docs?

**Comment by steven-murray** [comment]
I think possibly the use case here is that we might want to simulate a single snapshot of eg. HERA data, but in the final product we want the `integration_time` array to contain the correct ~9.6 sec so aid in calculating thermal noise etc. So I suppose you should be able to independently set the integration time and the snapshot time-stamps... maybe there should be a check that fails if integration_time > (time[1] - time[0]) if there's more than one time. But it seems OK if `integration_time < time[1] - time[0]` to me.
