### ISSUE TITLE
No mpirun warning outputs when essential quantities are not shared. 

### ISSUE THREAD

**Issue by nmahesh1412** [RadioAstronomySoftwareGroup/pyuvsim#433]
This was noted when passing multiple beams into the run and the beam_dict was not shared among all the mpirun processes. 
The simulation just stalled, didnt crash and didnt give a warning or error.

**Comment by jpober** [comment]
This was written in the Slack that seems to suggest a resolution:

> I was able to resolve this issue and have now successfully passed 2 beams into a pyuvsim.
> The main issue was that I didnt share the beam list dict among all the processes in the mpirun.
> But I will open a github issue to have better warning outputs from pyuvsim instead of just causing it to stall.

**Comment by nmahesh1412** [comment]
So I had passed dict_t to the `pyuvsim run` as follows without sharing it among all mpirun processes
`uv = comm.bcast(uv, root=0)
beam_list = comm.bcast(beam_list, root=0)
catalog_formatted.share(root=0)

start_time = time.time()
output_uv = pyuvsim.uvsim.run_uvdata_uvsim(
    input_uv=uv,
    beam_list=beam_list,
    **beam_dict=dict_t,**
    catalog=catalog_formatted,
    quiet=False,
)`

by adding :` dict_t = comm.bcast(dict_t, root=0)` before calling pyuvsim fixed the issue.

**Comment by nmahesh1412** [comment]
And not sharing beam_dict list just caused the code to stall without any warnings

**Comment by mkolopanis** [comment]
given that these lines are the quintessentially sharing for all sims, is there a harm just moving them into `run_uvdata_uvsim`?

https://github.com/RadioAstronomySoftwareGroup/pyuvsim/blob/80b9f6ac81205e2e27bc4071c908141d3681069b/pyuvsim/uvsim.py#L958-L961
