### ISSUE TITLE
Turn off warnings for GLEAM reader

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvsim#46]
Astropy doesn't think Jy/beam is a valid unit and warns us for EVERY source read from the GLEAM catalog.  We should silence these warnings until the world is ready for radio astronomy.

**Comment by jpober** [comment]
Turned off in tests for now.  But it's not clear why this is a problem at all given the astropy docs.

**Comment by jpober** [comment]
@bhazelton Did you look into this?  Any updates?

**Comment by bhazelton** [comment]
I did but I didn't figure it out. I got as far as looking up what the astropy docs were using as the list of valid coordinates and Jy/beam was in there so I was confused about why there was an error. I think we should verify that and then maybe reach out to astropy about what's going on.

**Comment by jpober** [comment]
Still somewhat of an issue when running simulations.

**Comment by jpober** [comment]
Fixed by astropy.
