### ISSUE TITLE
Memory usage

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvsim#49]
Big job (~3.7 million tasks) exceeded 100 GB memory limit.  Seems to have happened during task list generation.  Obviously an issue, needs investigation.

**Comment by aelanman** [comment]
A possibly approach to solving this: For big jobs, split the task list in several smaller task lists and scatter/gather those sequentially.
Alternatively: Scatter the meshgrid directly and generate task objects on separate ranks.

**Comment by jpober** [comment]
Original numbers come from a bug.  Now it seems like we use a factor of ~10 more in memory than naïvely expected.  Not atrocious, but not ready to call this something other than a bug just yet.

**Comment by jpober** [comment]
Size of task list itself is a factor of ~2.7 smaller than the memory increment from creating the task list.

**Comment by dannyjacobs** [comment]
Also, tasks take up 390 bytes when output. The factor 2.7 bloat occurs in uvdata_to_task_list during the meshgrid.

Proposed solution for after our first milestone on issue #56 (make task calculation local to nodes), and even just in time for input into the UVEngine.  Still debates about how to handle multi-scatter (aka scatter gather, aka hierarchical scatter).
