### ISSUE TITLE
Clean up

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvsim#51]
Code needs a thorough read through and reorganization before things get further out of hand.

**Comment by dannyjacobs** [comment]
Moved code to new files as planned (this made the profiling more complicated, but is functional)
re-Ordered input statements
_nearly_ python3 compatible
Coverage hasn't increased much.

**Comment by mkolopanis** [comment]
tests also need to be moved into separate files for each module now. (still have 1 massive test_uvsim.py) file
