### ISSUE TITLE
Wrapper to break up big sim into multiple jobs

### ISSUE THREAD

**Issue by aelanman** [RadioAstronomySoftwareGroup/pyuvsim#60]
To sidestepping memory / cpu limits for now, it would be useful to have a wrapper that reads parameters and splits the simulation into multiple smaller jobs (splitting over time or frequency).

**Comment by jpober** [comment]
This is still useful if we have jobs that die (e.g. out of memory) as opposed to simply taking a long time to run.  If anyone encounters a job that dies, please post info here!

**Comment by jpober** [comment]
The current architecture obviates the need for this.  We can reopen if jobs unexpectedly die.
