### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jpober** [RadioAstronomySoftwareGroup/pyuvsim#66]
Clear documentation of all input formats for reference simulations needs to be available.

**Comment by aelanman** [comment]
The parameter_docs branch starts on a documentation set with some info on the parameter files. We should set up a readthedocs site to load this information.

**Comment by jpober** [comment]
Information is on HERA wiki page, contains readme and path to files on Lustre.  Nithya was able to make sense of this info and run PRISim based on it.
