### ISSUE TITLE
unpolarized simulations with power pyuvbeams?

### ISSUE THREAD

**Issue by anguta** [RadioAstronomySoftwareGroup/pyuvsim#91]
pyuvbeam objects with power beams have Naxes_vec = 1 while uvsim assumes uvbeams have Naxes_vec =2.  pyuvsim currently appears to support unpolarized analytical beams by setting both e-field responses equal to the square root of the power beam but does not appear to support uvbeam power beams which can be useful for simple verification simulations.

**Comment by jpober** [comment]
Polarization is at the core of pyuvsim.  You could probably make this happen by changing a pyuvbeam object and not changing pyuvsim, though.  Is it ok for us to close this?

**Comment by jpober** [comment]
@anguta See previous comment.  Is this still an issue you want open?

**Comment by anguta** [comment]
I'm fine if this is closed.
